Algoritmo "exemploCrescente"

Var
   n1, n2 : inteiro

Inicio
      escreval("Digite dois números: ")
      leia(n1)
      leia(n2)
      
      enquanto n1 <> n2 faca
      
         se n1 < n2 entao
            escreval("Crescente!")
         senao
            escreval("Decrescente!")
         fimse
         
         escreval("Digite outos dois números: ")
         leia(n1)
         leia(n2)
      
      fimenquanto

      


Fimalgoritmo